name: "Compile"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  compile:
    name: "Compile Templates"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v2
      with:
        node-version: '24'
    - run: node config.js
