name: "Compile"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout respository
      uses: actions/checkout@v4
    - name: Init node env
      uses: actions/setup-node@v2
      with:
        node-version: '24'
    - name: Setup node env
      run: npm ci
    - name: Compile templates
      run: npm run compile
    - name: Commit changes
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git add -f build/
        git commit -m "Compile"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        
        
